### ISSUE TITLE
rbd status check fails - 

### ISSUE THREAD

**Issue by wyllys66** [kubernetes-incubator/external-storage#1002]
Using the ceph.com provisioner to create RBD images for persistent volumes exactly as described in the examples.

The RBD image is created successfully, however, the pod never completely starts and generates this error:

```
MountVolume.WaitForAttach failed for volume "pvc-77bb8120-c0df-11e8-bdb4-001e0b4843c4" : fail to check rbd image status with: (executable file not found in $PATH), rbd output: ()
```

root is not an option right now, we would like to just use the rbd provisioner if possible without installing rook and all of its dependencies.

**Comment by wongma7** [comment]
is 'rbd' installed on the nodes?

**Comment by wongma7** [comment]
we should document that ceph rbd utilities are required on nodes as a prerequisite

**Comment by wyllys66** [comment]
rbd utilities are part of ceph-common package.  

Just installing ceph-common is not enough, the node would also then need a minimal /etc/ceph/ceph.conf file in order for the rbd client to execute correctly.

**Comment by Paxa** [comment]
+1 for adding it to documentation. I had same issue

**Comment by exodussystem** [comment]
For OS like CoreOS, I cannot install ceph-common.
However, I can manage to get rbd/rados binary accessible by running Docker container 
with [ceph/container](https://github.com/ceph/ceph-container)

Source:
https://stackoverflow.com/questions/37996983/invoking-rbd-docker-from-kubernetes-on-coreos-returns-fork-exec-invalid-argume

In this case, I need to setup /etc/ceph/ceph.conf.
I got it work up to this step. When I brought up a PVC for MariaDB, I got this error 

_MountVolume.WaitForAttach failed for volume "pvc-d82e2dd3-41e8-11e9-aa1a-000c297f8172" : fail to check rbd image status with: (exit status 22), 
rbd output: (server name not found: ceph-mon.ceph.svc.cluster.local (Name or service not known) unable to parse addrs in 'ceph-mon.ceph.svc.cluster.local:6789' rbd: couldn't connect to the cluster! 
2019-03-08 21:27:01.924 7f3981d65900 -1 monclient: get_monmap_and_config cannot identify monitors to contact )
error_

_**The PVC was created successfully but it could be bound because RBD failed to check status.**_ 

Any idea?

**Comment by captainwenzi** [comment]
I'm getting the same error in Pod: MountVolume WaitForAttach failed for volume xxx: fail to check rbd image status with (executable file not found in $PATH), RBD OUTPUT: ()

I am using built-in k8s on Docker EE and by following the instruction(http://tutorial.kubernetes.noverit.com/content/ceph.html), I am able to create PVC with bounded PV using ceph-rbd storage class.

The Ceph cluster also returns HEALTH_OK with running monitors and osds. I have 3 monitors and 3 OSDs sharing the same 3 VMs and 1 k8s cluster with 3 worker nodes.

And I can get pv list when I run 'rbd ls' in all k8s worker node.

Anyone can advice the error msg - "executable file not found in $PATH" comes from which node or container?
