### ISSUE TITLE
NFS Demo link is not available

### ISSUE THREAD

**Issue by priteshchandaliya** [kubernetes-incubator/external-storage#1029]
https://github.com/kubernetes-incubator/external-storage/blob/v5.2.0/nfs/docs/demo
The link used in the nfs readme (with the hyper link as - here) for showing the demo does not exist.
Can you upload the demo at the link or update the link with the correct one.

**Comment by wongma7** [comment]
The demo guide was removed because it wasn't maintained, the quick start should have enough information, it's just less verbose/explanatory https://github.com/kubernetes-incubator/external-storage/tree/v2.0.0/nfs#quickstart. You can view the old demo here https://github.com/kubernetes-incubator/external-storage/tree/v2.0.0/nfs/docs/demo but not everything in it is true anymore, I will fix the broken link (by removing it)

.area nfs
