### ISSUE TITLE
[aws-efs] slow performance for multi-AZ mounts

### ISSUE THREAD

**Issue by caseylucas** [kubernetes-incubator/external-storage#1030]
I'm not sure if this is an aws efs provisioner issue but maybe someone has a thought on how to solve the performance problems I saw when using efs provisioner.

### Summary
NFS mounts from pods use the availability zone specific EFS mount endpoint (IP) based on the AZ where kube-dns runs not the AZ of the mounting pod. If the mounting pod and kube-dns are in the same AZ then EFS performance is typical.  If the mounting pod and kube-dns are in different AZs then all NFS traffic is sent over the cross-AZ link which adds latency that is very noticeable
for NFS file operations.

https://docs.aws.amazon.com/efs/latest/ug/mounting-fs-mount-cmd-dns-name.html

### Work around
~~I was able to work around the issue by scaling kube-dns so that each AZ had a kube-dns pod. Maybe I should have already done that?  Once the dns queries for the EFS mount point were AZ specific, EFS performance returned to typical.~~

Update: I was not able to work around the issue. I just got lucky with kube-dns being hit from the same AZ when I tested. I subsequently noticed other containers having the problem. Currently, I'm not sure how to get same AZ (best) performance out of EFS when using kubernetes.

### Issue?
Maybe this isn't an efs provisioner issue but maybe there is some way for the provisioner to do better.  Maybe it could attempt to mount the AZ specific endpoint? `availability-zone.file-system-id.efs.aws-region.amazonaws.com` Maybe the docs could point out this potential problem?

### Example performance problem
We noticed slow performance from a web server pod with a mounted EFS directory containing lots of small files (typical web server files). In one example EFS mounted directory `find . -print` would take 30 seconds when mounting cross AZ. When mounted in the same AZ the same command would take 4 seconds.

**Comment by wongma7** [comment]
Currently the provisioner is hardcoded to mount from the given zone, i.e. $GIVEN_ZONE.file-system-id.efs.aws-region.amazonaws.com . (It needs to be refactored anyway because some people don't want to use the AWS DNS name and have their own.)

We need to implement support for topologies (see https://kubernetes.io/docs/concepts/storage/storage-classes/#volume-binding-mode and https://kubernetes.io/docs/concepts/storage/storage-classes/#allowed-topologies) if we want the provisioner to be smart enough to handle multi-zone. I have not looked closely at it yet, it is pretty new, but my understanding is that the kubernetes scheduler will decide which zone the pod lands in and then the provisioner can create the PV in the same zone. Does that sound right?

/area aws/efs

**Comment by caseylucas** [comment]
@wongma7 Would you mind pointing me to the source that references `GIVEN_ZONE`?  I only saw https://github.com/kubernetes-incubator/external-storage/blob/master/aws/efs/cmd/efs-provisioner/efs-provisioner.go#L98 which implies that the zone-independent dns name is always being used.

**Comment by wongma7** [comment]
Oh my mistake, it's totally ignorant of zones at the moment. Either way the long-term solution is to implement the topology stuff.

**Comment by whereisaaron** [comment]
@wongma7 the `allowTopologies` doesn't appear to be useful here, since it just restricts the StorageClass. If you restrict the StorageClass to one AZ, then yes, you can get the Pod scheduled to the same AZ; but if that AZ fails the Pod will be unable to be scheduled. Which defeats the benefit of using EFS. Am I missing something?

I think any solution would have to occur at mount time, since you can't determine the IP address or per-AZ domain name until you you know the AZ where the Pod has been scheduled.

So at mount time, it would be a full solution, if you could either:
1. Ensure the `file-system-id.efs.aws-region.amazonaws.com` name is resolved by the VPC DNS end point.
2. Prefix the DNS name with the AZ in which the Pod has been scheduled, and resolve `availability-zone.file-system-id.efs.aws-region.amazonaws.com` via `kube-dns` or the VPC DNS endpoint, it won't matter.
