### ISSUE TITLE
[nfs-client] provitsioner is not allowed to use nfs volumes

### ISSUE THREAD

**Issue by PetrGlad** [kubernetes-incubator/external-storage#1145]
Upon nfs-client container deployment, I get the event
```
Error creating: pods "nfs-client-provisioner-5cf596db9d-" is forbidden: unable to validate against any security context constraint: [spec.volumes[0]: Invalid value: "nfs": nfs volumes are not allowed to be used]
```

So the nfs-client provisioner does not start.
The problem appears both applying rbac.yaml explicitly and installing with helm.

I tried to work around this by creating PV and referring to that in configuration - that helps provisioner to start. But then when I try to create containers that use NFS volumes they cannot be mounted, although nfs-client's logs says the PV was provisioned, and PVs status says it is Bound. The container startup error is  `MountVolume.SetUp failed for volume “nfs” : mount failed: exit status 32`
I can mount the NFS in Linux from node's console without problems.

Running Minishift v1.29.0+72fa7b2 (OKD/Openshift 3.11, CentOS) with nfs-utils installed on the node.
Configuration files from master branch (2019-03-06).

**Comment by wongma7** [comment]
The pod needs to be granted permissions to `use` an SCC that permits it to use nfs volumes, for example `hostmount-anyuid`. Alternatively, you can create a PV with the same NFS information, create a PVC to bind to that PV, and use the PVC in your nfs-client-provisioner pod because the `restricted` SCC will allow you to use pvc volumes.

See here for more info: https://docs.openshift.com/container-platform/3.11/admin_guide/manage_scc.html

**Comment by scphantm** [comment]
i tried that.  

`helm install --name nfs-client-provisioner --kubeconfig sa.kubeconfig stable/nfs-client-provisioner --set nfs.server=nfs-65-225 --set nfs.path=/kubernetes-test`

`oc adm policy add-scc-to-user hostmount-anyuid system:serviceaccount:default/nfs-client-provisioner`

It still can't start the pod.

**Comment by wongma7** [comment]
Is it possible to have helm render the replicaset yaml, change the securityContext and create the replicaset after? I am not too familiar with helm, once you get it working I would also open an issue with the charts repo to make it optional.

Any idea where the range  [1000000000, 1000009999] comes from? It might be an annotation on the project, what does the project yaml look like? Can you paste the privileged scc yaml here?

**Comment by scphantm** [comment]
Well, i tried deleting everything and creating it by hand instead of using helm.  Error message changed...

`Error creating: pods "nfs-client-provisioner-67c58f4645-" is forbidden: unable to validate against any security context constraint: [spec.volumes[0]: Invalid value: "nfs": nfs volumes are not allowed to be used]`

problem is this is after i gave the service account `privileged ` and `hostmount-anyuid`

**Comment by supriya-premkumar** [comment]
You need to add `nfs` volume in your PodSecurityPolicy spec.

**Comment by jdorel** [comment]
Can be resolved with `oc adm policy add-scc-to-user hostmount-anyuid -z nfs-client-provisioner`

**Comment by gimmely** [comment]
> Can be resolved with `oc adm policy add-scc-to-user hostmount-anyuid -z nfs-client-provisioner`

This worked for me after re-deployment.
