### ISSUE TITLE
NFS-Client uses deprecated Deployment API Version

### ISSUE THREAD

**Issue by zimmertr** [kubernetes-incubator/external-storage#1228]
Hello, the [deployment manifest](https://github.com/kubernetes-incubator/external-storage/blob/master/nfs-client/deploy/deployment.yaml#L7) for NFS-Client currently uses `extensions/v1beta1` which has been deprecated in Kubernetes 1.16. 

Working on a PR now.

**Comment by zimmertr** [comment]
Pull Request here: https://github.com/kubernetes-incubator/external-storage/pull/1230

**Comment by koelnconcert** [comment]
The "compiled" manifests seems to be updated, however the individual files in `nfs-client/deploy/objects` are still using the deprecated apiVersion.

**Comment by zimmertr** [comment]
Thanks for saying that. I'll open another PR today to address that. 

I never noticed because I don't use this project like most other people. I just reused the logic in this repo and noticed it stopped working so I went back to the source to commit a fix upstream.

https://github.com/zimmertr/Bootstrap-Kubernetes-with-QEMU/blob/master/playbooks/optional/deploy_nfs_provisioner.yml

**Comment by wongma7** [comment]
opened https://github.com/kubernetes-incubator/external-storage/pull/1270/files to fix this repo-wide

**Comment by silborynirmata** [comment]
The above isn't enough for more modern k8 apis.  You also need.  
selector:
    matchLabels:
        app: efs-provisioner

**Comment by darewreck54** [comment]
Any update on this?

**Comment by nikhita** [comment]
Thanks for reporting the issue!

This repo is no longer being maintained and we are in the process of archiving this repo. Please see https://github.com/kubernetes/org/issues/1563 for more details.

If your issue relates to nfs provisioners, please create a new issue in https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner or https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner.

Going to close this issue in order to archive this repo. Apologies for the churn and thanks for your patience! :pray:
