### ISSUE TITLE
Multiarch container manifest

### ISSUE THREAD

**Issue by yhaenggi** [kubernetes-incubator/external-storage#1250]
Could you please provide multiarch containers (docker manifest) for amd64, arm and aarch64?

**Comment by nikhita** [comment]
Thanks for reporting the issue!

This repo is no longer being maintained and we are in the process of archiving this repo. Please see https://github.com/kubernetes/org/issues/1563 for more details.

If your issue relates to nfs provisioners, please create a new issue in https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner or https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner.

Going to close this issue in order to archive this repo. Apologies for the churn and thanks for your patience! :pray:
