### ISSUE TITLE
Can we get the tag for nfs-provisioner 2.3.0 on quay.io?

### ISSUE THREAD

**Issue by lurraca** [kubernetes-incubator/external-storage#1273]
I would like to update the [nfs-server-provisioner helm chart ](https://github.com/helm/charts/blob/master/stable/nfs-server-provisioner/values.yaml) to have at least the [nfs-provisioner v2.3.0](https://github.com/kubernetes-incubator/external-storage/tree/nfs-provisioner-v2.3.0). For that I would need the tag v2.3.0 to be released on [quay.io/repository/kubernetes_incubator/nfs-provisioner](https://quay.io/repository/kubernetes_incubator/nfs-provisioner?tab=tags).

## Additional Questions
* What's the process for new tags to be released on the image repository? 
* Is this is something that anyone could do or does it has to be a core contributor of external-storage?

**Comment by wongma7** [comment]
> What's the process for new tags to be released on the image repository?
Tag created on github and then corresponding image manually built and pushed. (Other projects in this repo don't need manual build+push, it's only  nfs-provisioner because it's hosted at kubernetes_incubator quay org instead of external_storage org, and I guess now is a good time to move it as the whole repo is being deprecated soon). Releases are made sporadically, there's no schedule

Yes, only some core contributor can do it. I am the only maintainer

**Comment by cedricve** [comment]
Hello,

I would also love to benefit from this merged PR kubernetes-incubator/external-storage#1214.

I've seen that there is a 2.3.0 tag on Github, but no image on quay.io (https://quay.io/repository/kubernetes_incubator/nfs-provisioner?tag=latest&tab=tags)

We are trying to provide a fix to helm, so we can make use of this feature (#20371).

Can we make a new build available?

Thank you!

**Comment by stek29** [comment]
#1262 duplicate

**Comment by wongma7** [comment]
I've pushed a new image.

In the future please feel free to email me mattwon @ amazon.com or find me on slack @wongma7 to get a release. It's only NFS that needs manual pushing after git tagging, it's tedious and I want to fix it for the future.

**Comment by lurraca** [comment]
@wongma7 Thanks! This issue can be close.
