### ISSUE TITLE
[EFS] Allow customizing name of directory created

### ISSUE THREAD

**Issue by yuvipanda** [kubernetes-incubator/external-storage#1281]
https://github.com/kubernetes-incubator/external-storage/blob/master/aws/efs/cmd/efs-provisioner/efs-provisioner.go#L234 hard codes the path of the locally created directory. While this works for the general case, I'd love for this to be customizable.

We run interactive compute environments for users via JupyterHub, and use EFS for storing user home directories. Currently, the cluster is stateless - if we take down a cluster and move to a new one, user home directories aren't lost. However, since EFS provisioner puts the randomly generated name of the PV in the user directory, we'll have to try save / restore the PV objects from one cluster to the next. This isn't necessary for our use case, and I'd love to avoid it.

If we can customize the name of the PV / name of the local directory being created via an env var, that will help a lot with this use case.

Am happy to work on a PR!

**Comment by luozhihua** [comment]
With the same requirements, I faced the same pain every time I migrated the cluster and needed to manually migrate PV and PVC.

**Comment by valeriozhang** [comment]
+1 haha definitely need this

**Comment by jwitrick** [comment]
Is there any update on this issue? And/Or does an issue have to be opened first with: https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner to enable those options?

**Comment by nikhita** [comment]
Thanks for reporting the issue!

This repo is no longer being maintained and we are in the process of archiving this repo. Please see https://github.com/kubernetes/org/issues/1563 for more details.

If your issue relates to nfs provisioners, please create a new issue in https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner or https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner.

Going to close this issue in order to archive this repo. Apologies for the churn and thanks for your patience! :pray:
