### ISSUE TITLE
Multi Arch Image

### ISSUE THREAD

**Issue by adi90x** [kubernetes-incubator/external-storage#1292]
Hello, 
There is an image for arm64 and one for x64, wouldn't it be possible to build a multiarch manifest to enable nfs-client in multi arch environment ? 
Regards,

**Comment by mcristina422** [comment]
It seems like multiarch/alpine has arm64 images and https://github.com/kubernetes-incubator/external-storage/pull/1296/files is open switching to multiarch/alpine. That's still only for arm7 though, another builder would be needed for arm64

**Comment by nikhita** [comment]
Thanks for reporting the issue!

This repo is no longer being maintained and we are in the process of archiving this repo. Please see https://github.com/kubernetes/org/issues/1563 for more details.

If your issue relates to nfs provisioners, please create a new issue in https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner or https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner.

Going to close this issue in order to archive this repo. Apologies for the churn and thanks for your patience! :pray:
