### ISSUE TITLE
efs-provisioner should make FILE_SYSTEM_ID and AWS_REGION optional

### ISSUE THREAD

**Issue by mingfang** [kubernetes-incubator/external-storage#1299]
The verification on startup fails when FILE_SYSTEM_ID and AWS_REGION is not set.

https://github.com/kubernetes-incubator/external-storage/blob/9dc519099ae7de7a2bef7ab22bf554e79b8b301b/aws/efs/cmd/efs-provisioner/efs-provisioner.go#L84

This verification should be skipped instead

**Comment by leepatrick-goop** [comment]
I should be able to set the endpoint as an IP address to allow mounting from across a peering connection from another VPC/region as per AWS instructions for doing so.

**Comment by nikhita** [comment]
Thanks for reporting the issue!

This repo is no longer being maintained and we are in the process of archiving this repo. Please see https://github.com/kubernetes/org/issues/1563 for more details.

If your issue relates to nfs provisioners, please create a new issue in https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner or https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner.

Going to close this issue in order to archive this repo. Apologies for the churn and thanks for your patience! :pray:
