### ISSUE TITLE
1.16 changes to remove deprecated APIs

### ISSUE THREAD

**Issue by dloiko** [kubernetes-incubator/external-storage#1303]
In kubernetes 1.16 there are a number of API's being deprecated [1]. I noticed that there's an issue to track this for NFS-client [2], however I wanted to open this issue to confirm what other changes are needed in this repository. I'm mainly concerned about the snapshot functionality.

I see that there is a PR open for updating this [3], which appears to convert the deprecated API's in the repo to the new API's. This issue is mainly for tracking to ensure this project is ready for the deprecations in 1.16.

[1] https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
[2] https://github.com/kubernetes-incubator/external-storage/issues/1228
[3] https://github.com/kubernetes-incubator/external-storage/pull/1270

**Comment by nikhita** [comment]
Thanks for reporting the issue!

This repo is no longer being maintained and we are in the process of archiving this repo. Please see https://github.com/kubernetes/org/issues/1563 for more details.

If your issue relates to nfs provisioners, please create a new issue in https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner or https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner.

Going to close this issue in order to archive this repo. Apologies for the churn and thanks for your patience! :pray:
