### ISSUE TITLE
About cephfs StorageClass automatically creating PV and creating directory names on the cephfs service file system

### ISSUE THREAD

**Issue by JokerDevops** [kubernetes-incubator/external-storage#1310]
I have now deployed the kubernetes environment and the cephfs storage cluster. Now I can automatically create PV to bind to it by creating PVC and automatically create the corresponding directory on the cephfs file system. However, the names of the directories on the cephfs file system are randomly generated, and the relationship between the directory of the cephfs file system and PVC&PV cannot be found.
How do I set the automatically created cephfs file system directory name to correspond to PVC&PV?
Is the version I used not supported? Which version supports this feature?

**Comment by nikhita** [comment]
Thanks for reporting the issue!

This repo is no longer being maintained and we are in the process of archiving this repo. Please see https://github.com/kubernetes/org/issues/1563 for more details.

If your issue relates to nfs provisioners, please create a new issue in https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner or https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner.

Going to close this issue in order to archive this repo. Apologies for the churn and thanks for your patience! :pray:
