### ISSUE TITLE
ceph-provisioner: mount options in a storage class definition

### ISSUE THREAD

**Issue by xclan** [kubernetes-incubator/external-storage#1313]
Is it possible to describe mount option in a storage class in order to apply to all new pv and ceph images that are mounted at worker node?

In particular I am interested in the option _netdev. 

My question is related to reboot problems in which the server does not return due to the fact that the volumes did not have time to unmount before the network stack was unloaded.

Or maybe there are still some other opportunities to achieve the goal?

**Comment by nikhita** [comment]
Thanks for reporting the issue!

This repo is no longer being maintained and we are in the process of archiving this repo. Please see https://github.com/kubernetes/org/issues/1563 for more details.

If your issue relates to nfs provisioners, please create a new issue in https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner or https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner.

Going to close this issue in order to archive this repo. Apologies for the churn and thanks for your patience! :pray:
