### ISSUE TITLE
nfs-server-provisioner memory usage requirements

### ISSUE THREAD

**Issue by sadortun** [kubernetes-incubator/external-storage#1315]
Hi ! 

Follow up of #540 

We run a low traffic cluster with about 10 nfs mounts and we have started using the nfs-provisioner a few days ago and the memory used keep climbing (until it failed completely) 

![image](https://user-images.githubusercontent.com/794449/80971160-523fd480-8dea-11ea-9cec-a7f12ab476a4.png)

Is this a bug ? Can  you clarify the docs on how much memory is required ?

Thanks,
Samuel

**Comment by nikhita** [comment]
Thanks for reporting the issue!

This repo is no longer being maintained and we are in the process of archiving this repo. Please see https://github.com/kubernetes/org/issues/1563 for more details.

If your issue relates to nfs provisioners, please create a new issue in https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner or https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner.

Going to close this issue in order to archive this repo. Apologies for the churn and thanks for your patience! :pray:
