### ISSUE TITLE
nfs-client-provisioner error runAsNonRoot

### ISSUE THREAD

**Issue by avarf** [kubernetes-incubator/external-storage#1325]
I want to install nfs-client-provisioner on a cluster but I am getting `CreateContainerConfigError` and when I get the describe command I get below error:
```bash
kubectl -n nfs describe pod nfs-client-nfs-client-provisioner-9c94f56bf-57bdw

Events:
  Type     Reason     Age                From                            Message
  ----     ------     ----               ----                            -------
  Normal   Scheduled  51s                default-scheduler               Successfully assigned nfs/nfs-client-nfs-client-provisioner-9c94f56bf-57bdw to wws-futurex-worker-02
  Normal   Pulling    50s                kubelet, wws-futurex-worker-02  Pulling image "quay.io/external_storage/nfs-client-provisioner:v3.1.0-k8s1.11"
  Normal   Pulled     35s                kubelet, wws-futurex-worker-02  Successfully pulled image "quay.io/external_storage/nfs-client-provisioner:v3.1.0-k8s1.11"
  Warning  Failed     13s (x4 over 35s)  kubelet, wws-futurex-worker-02  Error: container has runAsNonRoot and image will run as root
  Normal   Pulled     13s (x3 over 35s)  kubelet, wws-futurex-worker-02  Container image "quay.io/external_storage/nfs-client-provisioner:v3.1.0-k8s1.11" already present on machine

```

How can I fix the `Error: container has runAsNonRoot and image will run as root`?

**Comment by nikhita** [comment]
Thanks for reporting the issue!

This repo is no longer being maintained and we are in the process of archiving this repo. Please see https://github.com/kubernetes/org/issues/1563 for more details.

If your issue relates to nfs provisioners, please create a new issue in https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner or https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner.

Going to close this issue in order to archive this repo. Apologies for the churn and thanks for your patience! :pray:
