### ISSUE TITLE
nfs-client ignores PVC AccessMode

### ISSUE THREAD

**Issue by dkolepp** [kubernetes-incubator/external-storage#1327]
It seems that the nfs-client does not consider the access mode of a PVC when provisioning.  If the nfs-client is the default storage class, and a user requests a RWO or ROX PVC, an error is not returned if the NFS storage is actually RWX.  Is that expected?

**Comment by nikhita** [comment]
Thanks for reporting the issue!

This repo is no longer being maintained and we are in the process of archiving this repo. Please see https://github.com/kubernetes/org/issues/1563 for more details.

If your issue relates to nfs provisioners, please create a new issue in https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner or https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner.

Going to close this issue in order to archive this repo. Apologies for the churn and thanks for your patience! :pray:
