### ISSUE TITLE
test-pod.yaml problem

### ISSUE THREAD

**Issue by luo964973791** [kubernetes-incubator/external-storage#1338]
test-pod.yaml does not write multiple copies, it is problematic to repeatedly test the mounting of multiple copies

**Comment by nikhita** [comment]
Thanks for reporting the issue!

This repo is no longer being maintained and we are in the process of archiving this repo. Please see https://github.com/kubernetes/org/issues/1563 for more details.

If your issue relates to nfs provisioners, please create a new issue in https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner or https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner.

Going to close this issue in order to archive this repo. Apologies for the churn and thanks for your patience! :pray:
