### ISSUE TITLE
nfs-provisioner: Improvement: Health check

### ISSUE THREAD

**Issue by webnull** [kubernetes-incubator/external-storage#1341]
Hi,

I noticed that when I have for example 2 pods, and 1 of them for unknown reason is having a hanged up NFS connection. When both pods would get a hanged up connection, then whole cluster would be without a storage.

I suggest that a health check there can be done - if the mounted volume does not respond in eg. 10 seconds for simple "touch" or directory listing, then we the pod is marked as unhealthy and should be restarted.

**Comment by TonyBogdanov** [comment]
+1

**Comment by nikhita** [comment]
Thanks for reporting the issue!

This repo is no longer being maintained and we are in the process of archiving this repo. Please see https://github.com/kubernetes/org/issues/1563 for more details.

If your issue relates to nfs provisioners, please create a new issue in https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner or https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner.

Going to close this issue in order to archive this repo. Apologies for the churn and thanks for your patience! :pray:
