### ISSUE TITLE
Question: Is it possible to migrate to another nfs server ?

### ISSUE THREAD

**Issue by bloudman** [kubernetes-incubator/external-storage#1342]
Hi,
I have a question, and i don't find any answer. Maybe you can help me ... 
In fact I have to migrate my pvc to another NFS Server. 
All datas will remain exactly the same (same name same files same folders... ) the only change will be the IP of the server.

I tried to upgrade the chart with the new IP : nfs.server.ip parameter but it did not change existing volumes.

Can you help me to figure out how to do the manipulation ? I tried to change the IP directly in the PV but nothing work.

I know it is a question that is maybe not in your scope but maybe you have an idea ...

**Comment by nikhita** [comment]
Thanks for reporting the issue!

This repo is no longer being maintained and we are in the process of archiving this repo. Please see https://github.com/kubernetes/org/issues/1563 for more details.

If your issue relates to nfs provisioners, please create a new issue in https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner or https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner.

Going to close this issue in order to archive this repo. Apologies for the churn and thanks for your patience! :pray:
