### ISSUE TITLE
Persistent Volume fails to mount to pod

### ISSUE THREAD

**Issue by vbottu** [kubernetes-incubator/external-storage#1349]
Hi,
I've deployed latest version of client provisioner on kubernetes and when I create the pvc, a pv id dynamically created and when I try to mount that volume into a pod it fails to mount with access denied error. 
`mount.nfs: access denied by server while mounting *********:/K8sdev/test-dev-springboot-sample-claim-pvc-68625`

I am able to mount the nfs share on all the nodes manually without any issues

**Comment by nikhita** [comment]
Thanks for reporting the issue!

This repo is no longer being maintained and we are in the process of archiving this repo. Please see https://github.com/kubernetes/org/issues/1563 for more details.

If your issue relates to nfs provisioners, please create a new issue in https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner or https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner.

Going to close this issue in order to archive this repo. Apologies for the churn and thanks for your patience! :pray:
