### ISSUE TITLE
local-volume image is not accessible for public

### ISSUE THREAD

**Issue by kesavkolla** [kubernetes-incubator/external-storage#140]
Current image for local-volume is hosted at `gcr.io/msau-k8s-dev/local-volume-provisioner:latest` which is not available for publically.  Can you please push the local-volume-provisioner to quay so everyone can use it.

**Comment by wongma7** [comment]
It's still in development and not fully functional yet so I think this is
intentional. The image tag will be updated when it's ready and pushed, the
plan is for around kubernetes 1.7 release time as it will only work with 1.7

**Comment by kesavkolla** [comment]
In current version 1.6.4 how can I use `statefulset` feature on local cluster?

**Comment by wongma7** [comment]
Officially, there is no way. You can try the nfs provisioner https://github.com/kubernetes-incubator/external-storage/tree/master/nfs which will work locally, it can auto-create nfs pvs inside a hostPath. Or **at your own risk** read through this issue here https://github.com/kubernetes-incubator/external-storage/issues/15 and see what other folks have created as temporary solutions.

**Comment by wongma7** [comment]
fixed via https://github.com/kubernetes-incubator/external-storage/pull/170

image is now at "quay.io/external_storage/local-volume-provisioner:latest"
