### ISSUE TITLE
nfs-client-provisioner create folder with 755, not 777

### ISSUE THREAD

**Issue by KinOSurvival** [kubernetes-incubator/external-storage#149]
I'm having an issue that all the folder are created with 755, not 777

When I go into the pod, quay.io/external_storage/nfs-client-provisioner:v1, I can see created folders under /persistentvolumes , and I can chmod 777 to those folders, so it shouldn't be permission problem.

Any ideas what's the problem? Thanks in advance.

**Comment by KinOSurvival** [comment]
PS: trying setting umask to 0 in the terminal , not helping

**Comment by KinOSurvival** [comment]
seems after the code
if err := os.MkdirAll(fullPath, 0777); err != nil {
		return nil, errors.New("unable to create directory to provision new pv: " + err.Error())
}

we have to invoke os.chmod(fullPath,0777), because umask is chaning the permission.

Or we can use
oldMask := syscall.Umask(0)
os.Mkdir(fullPath, 0777)
syscall.Umask(oldMask)

**Comment by wongma7** [comment]
yes. PR to fix this welcome :)

**Comment by wongma7** [comment]
fixed, will be present in nfs-client-provisioner:v2.0.0 (slight change in version format...)

**Comment by yuchaoran2011** [comment]
Hi @wongma7, are you sure this is fixed? I'm still seeing 755 permission:
`drwxr-xr-x    3 root     root          4096 Oct 10 01:54 persistentvolumes`
I installed the provisioner chart with the default setting, which uses the latest image: https://github.com/helm/charts/blob/master/stable/nfs-client-provisioner/values.yaml#L10

**Comment by yuchaoran2011** [comment]
Ok I saw the following error message when provisioning a new PV:

cluster.local/anxious-raccoon-nfs-client-provisioner_anxious-raccoon-nfs-client-provisioner-646b8bc8b4-jg924_9ad0ec75-ccf8-11e8-b81b-0a580a800207  failed to provision volume with StorageClass "nfs-client": unable to create directory to provision new pv: mkdir /persistentvolumes/default-claim1-pvc-7e821f54-ccfc-11e8-8439-0238590a06be: permission denied

And it came from https://github.com/kubernetes-incubator/external-storage/blob/master/nfs-client/cmd/nfs-client-provisioner/provisioner.go#L70. So it failed when creating a directory with 777 permission. I'm on OpenShift. Does anyone have an idea what I'm missing?

**Comment by wongma7** [comment]
@yuchaoran2011 The nfs-client provisioner needs permission to write to /persistentvolumes/ . What you can do is change the group owner of /persistentvolumes/ to e.g. 5555 and then edit your provisioner pod to have supplementalGroup 5555 so that it can write to the share. See here for more info https://docs.openshift.com/container-platform/3.11/install_config/persistent_storage/pod_security_context.html#supplemental-groups

**Comment by yuchaoran2011** [comment]
@wongma7 Thanks for the reply. My issue is that I can't do any `chmod` or `chgrp` command inside the provisioner pod. "Operation not permitted". Still trying to figure out the right permission settings.

**Comment by wongma7** [comment]
@yuchaoran2011 the provisioner pod probably isn't allowed to run as root (for good reason) so you may need to mount the nfs server some other place where you can manipulate its permissions

**Comment by yuchaoran2011** [comment]
@wongma7 Got it to work now. Thanks!

**Comment by petermicuch** [comment]
Hi @yuchaoran2011, what exactly have you done? I got the same issue. I installed nfs-client provisioner using helm and it was working fine, but after reinstall and new installation, I also get message "failed to provision volume with StorageClass "nfs-client": unable to create directory to provision new pv". When I do "sh" to the pod, I am unable to chmod 777, since I am not root.
