### ISSUE TITLE
Move Ceph RBD provisioner from in-tree to out of tree

### ISSUE THREAD

**Issue by childsb** [kubernetes-incubator/external-storage#200]
The CEPH RBD provisioner is in-tree.  The sig-storage community is requesting that the ceph RBD provisioner move out of tree.

This issue to track the effort. There is no current owner or scheduling of the work, only the request by the community.  If anyone has requirements or wishes to sign up for design, development or review please comment here.

**Comment by rootfs** [comment]
@cofyc @weiwei04 are you interested in working on it?

**Comment by wongma7** [comment]
cc https://github.com/kubernetes-incubator/external-storage/issues/99

**Comment by cofyc** [comment]
hi, @rootfs 

I and @weiwei04 are interested in working on it. Currently, we are running a few k8s clusters with Ceph RBD support. Any suggestions about how to do it and collaborating with sig-storage community would be appreciated.

**Comment by rootfs** [comment]
@cofyc thanks!

There is a [cephfs provisioner](https://github.com/kubernetes-incubator/external-storage/tree/master/ceph/cephfs) under ceph. You can write a ceph/rbd provisioner, and get the Kubernetes RBD provisioner there.

**Comment by cofyc** [comment]
@rootfs 
ok, I am working on it.

**Comment by alanmeadows** [comment]
@childsb Since you opened the "rewriting some bits" door, one of the issues we struggle with is passing _[client]_ options down at mount time.

See [ceph.conf](https://github.com/ceph/ceph/blob/master/src/sample.ceph.conf#L442) examples to do things like tune rbd cache policy, writethrough, etc behavior from an rbd client perspective.

Now, forgive me as I start to enter areas of my own ignorance - the need to me is clear but its relevancy to the rbd provisioner is not. Its unclear whether the provisioning workflow would play any role here as the kubelet actually performs the rbd device hookups and mounting and it is at this point these settings would be (and are not currently) taken into account.  I imagine the goal is to also take the kubelet rbd client connectivity code also out of tree otherwise I'm confused where this is going ultimately.  In any event, I could imagine a desire to be able to control client settings such as this with provisioner specific PVC metadata to drive these client options on a per PVC basis so the kubelet could exercise them at the time it plumbs up the rbd device.  In any event, at the very least I thought it would be worth while to publicly announce this client-tuning need to those far smarter then myself to decide where it ultimately belongs.

**Comment by cofyc** [comment]
@wongma7  I'm guessing this issue can be closed now, [RBD provisioner](https://github.com/kubernetes-incubator/external-storage/tree/master/ceph/rbd) is already in external-storage.

**Comment by kfox1111** [comment]
Should it be kept open until the in tree version is removed? Right now, its a copy more then a move.
