### ISSUE TITLE
[efs-provisioner] persistentVolumeReclaimPolicy: retain doesn't work

### ISSUE THREAD

**Issue by mjsilva** [kubernetes-incubator/external-storage#209]
Hi guys,

I've been testing the EFS provisioner to allow our pods to create EFS volumes on the fly and provide a nice abstraction to a "unlimited" filesystem the pods can use.

This has been working great but I'd love it to allow to retain the data if the pod is deleted.

Is this possible?

I've tried to `kubectl patch pv pvc-2d282439-5c7f-11e7-83f9-0642293e4557 -p '{"spec":{"persistentVolumeReclaimPolicy":"Retain"}}'` but it didn't really work. The data is deleted as soon as I delete my deployment.

Thanks

**Comment by mjsilva** [comment]
After digging a bit on this I reckon the problem might have been because I was mounting `/var`. I mounted the EFS on another machine and although I could see the folder created by the EFS-provisioner I didn't see any files inside, which leads me to believe that the container was writing on itselfs. After changing it to `/var/lib/grafana` the data was kept after delete/create the deployment and I could see it inside the EFS.

Here's a `df -h` on the problematic container
```
root@tm-grafana-2903206615-l2svr:/# df -h
Filesystem                                                                                                                    Size  Used Avail Use% Mounted on
overlay                                                                                                                        94G   15G   75G  17% /
tmpfs                                                                                                                         3.9G     0  3.9G   0% /dev
tmpfs                                                                                                                         3.9G     0  3.9G   0% /sys/fs/cgroup
fs-e84fa8d1.efs.ap-southeast-2.amazonaws.com://persistentvolumes/tm-grafana-storage-pvc-2d282439-5c7f-11e7-83f9-0642293e4557  8.0E  428M  8.0E   1% /var
/dev/xvda1                                                                                                                     94G   15G   75G  17% /etc/hosts
shm                                                                                                                            64M     0   64M   0% /dev/shm
tmpfs                                                                                                                         3.9G   12K  3.9G   1% /var/run/secrets/kubernetes.io/serviceaccount
```

**Comment by mjsilva** [comment]
@wongma7 thanks for developing this great plugin! Can you clarify the behaviour of the delete? Are the RECLAIMPOLICY on the pv disregarded and the volume is only deleted once the claim is deleted other than that it persists?

**Comment by wongma7** [comment]
The provisioner will respect the pv's reclaimpolicy. This means when the corresponding pvc is deleted: if Retain, neither the pv nor its data are deleted; if Delete, both are deleted. Nothing should happen if just the pod or deployment is deleted, it only matters when the pvc is deleted.

As you've done, you must manually patch the PV because the provisioner doesn't yet support auto creating Retain pvs (see https://github.com/kubernetes/kubernetes/pull/47987)

Now, the data loss you've observed when deleting the pod is consistent with my understanding of how docker works when you mount a file system (efs) on top of an existing file system that already has contents in it (var). It will overlay the two and you lose the writes that you thought you were making to efs as soon as you delete the pod

Hope this helps, feel free to ask for more clarification

**Comment by mjsilva** [comment]
Thanks mate that clarified. Feel free to close this.

**Comment by wongma7** [comment]
:+1:
