### ISSUE TITLE
[local-volume] Create Volume Sub-Folder

### ISSUE THREAD

**Issue by adrianliechti** [kubernetes-incubator/external-storage#250]
Hi Kubernets Team,

after quite some long nights we were able to setup a cluster with local volumes using the dynamic local volume provisioner and plan to introduce it in a bigger project for dynamic databases.

but we struggle with some conceptional problems. as far as we understand:
- you set up a hostdir for each storage-class (eg. /mnt/disks/)
- within that folder, you mount disks (vol1, vol2, whatever...)
- if an app requests a pvc using that class, *one* of the /mnt/disks/{volume} is bounded exclusively

are we correct on this? if so, we see some issues:

- regardless the pvc size request, a whole disk is consumed by a generated pv
- a disk is not used for other pv(s)

solution A could be to:
- mount the disk as /mnt/disks and generate some empty folder within that (vol1, vol2 etc.)
- the problem is: there is no storage isolation

solution B could be:
- create loop-filesystems on the disk with different sizes and mount them under /mnt/disks/
- but these volumes would be needed to generate upfront - and it's hard to determine a good mix of volume sizes
- the same applies for disk partitions

these things do not sound very "dynamic"... We think a great optional feature would be to:
- let the provisioner create a subfolder by itself under the storage-class hostdir: eg. local-pv-134325
- ensure quota on that directory (based on the pvc size request)

do you have an idea / rough help to understand the best way with the current state, assuming the use case is
- mariadb with local persistent volues
- the size of the dbs is based on a service catalog
- the size could grow by updating the plan

thank you super much for any suggestions

Best, Adrian

**Comment by ddysher** [comment]
Yes, you are correct about current status.  Right now, the provisioner is pretty static. There's no dynamic provisioning; all it sees are directory (even not mount point).  Thus, each PVC bounds to a PV which effectively a path under `/mnt/disks`.  There is currently no way to share a single directory from provisioner side.
> but we struggle with some conceptional problems. as far as we understand:
> you set up a hostdir for each storage-class (eg. /mnt/disks/)
> within that folder, you mount disks (vol1, vol2, whatever...)
> if an app requests a pvc using that class, one of the /mnt/disks/{volume} is bounded exclusively

> are we correct on this? if so, we see some issues:
> regardless the pvc size request, a whole disk is consumed by a generated pv
> a disk is not used for other pv(s)

Both are viable solutions.  If you don't care about capacity isolation, solution A is the easiest; for solution B, you have to have a good guess of how to partition the disk.  btw, if u have access to raw disk, i'd suggest using lvm instead of loop device for better performance.  Both solutions require manual setup and do not offer performance isolation.
> solution A could be to:

Dynamic provisioning is planned for 1.9, but there's nothing prevent you from writing your own :)  One possible solution is to create a provisioner listening pvc of a custom storage class, create partitions, mkfs and bind mount to `/mnt/disks/{volume}`.  
> these things do not sound very "dynamic"... We think a great optional feature would be to

/cc @msau42

**Comment by msau42** [comment]
The reason why dynamic provisioning is not supported yet is because it's very hard to do for local storage with the current provisioning architecture.  Namely, you could listen to the PVCs, but which node should be the one that provisions for that PVC?  To make a proper decision, the provisioning workflow should be integrated with pod scheduling.  Over the next few releases, we'll be working on integrating pod scheduling closer to volume binding and provisioning, but it's a big architectural change and will take some time.

So in the meantime, I would recommend either option.  Maybe you could have a script to partition disks based on the service catalog size request. 

Another thought: The primary use case we targeted for the initial local storage design is for high performance distributed datastores.  For the best performance, they typically want to reserve the entire disk and do not want to share that disk with others.  If you are ok with sharing disks with others in terms of performance, then why not put a distributed fs layer like Gluster on top of them instead of using local disks directly?  You will get the benefit that your application is more highly available in case of node failures.  There are also other many other companies that are looking at providing distributed block/fs storage for Kubernetes.

**Comment by adrianliechti** [comment]
thank you super much for both of your feedbacks! that helped a lot!
(and sorry for the late answer due some vacation)

at this point we try to avoid introducing of gluster (or likewise) to easy the transition at our customer. also accessing the vsphere layer is sadly not possible due existing security and oss/bss processes in a timely manner...

we decided to go in this direction at this point:

we run a script to:
- monitor available local-volume pvs on each node
- keep the number on a defined minimum (eg. 5)
- delete data of unbounded volumes after x days

we accept:
- that storage isolation is not possible and monitor the amount of each directory
- an uneven usage of storage on the individual nodes


do you already have a rough idea what will be the features of local-volumes in 1.9 and what to expect on how they work?
this would help us to plan our workarounds - or if we need to find project names for our hacks :)

**Comment by msau42** [comment]
Hi @adrianliechti, if you use the local volume external provisioner, it will automatically delete the data immediately when the PV is released (PVC is deleted), and it will automatically create the PV when it detects a new directory.  So if you use that, then your script just needs to monitor the disk usage and create new directories as needed.

As for timeline, 1.8 I plan to get a design out for scheduler and binding integration, and potentially an alpha implementation if there's time.  If not, then 1.9 for sure.  After that, then I can start looking into dynamic provisioning, which will probably be at least another release out.

**Comment by adrianliechti** [comment]
we created a small PoC using a provisioner and flexvolume plugin to achive dynamic local volumes:
[/k8s-localflex-provisioner](https://github.com/monostream/k8s-localflex-provisioner)

it replaces a bash-script on each node to permanently ensure 10 fresh local-volumes to get claimed by pods - and brings the positive effects that volumes are getting deleted as well :)

**Comment by msau42** [comment]
Rancher has also created a host path provisioner that creates directories on demand.  But it doesn't do the balancing as you mentioned.

Proper dynamic provisioning support with capacity isolation is being tracked here: https://github.com/kubernetes/enhancements/issues/562

/close
