### ISSUE TITLE
nfs-provisioner fails with v.1.0.8

### ISSUE THREAD

**Issue by mmaquevice** [kubernetes-incubator/external-storage#263]
When I upgrade from `quay.io/kubernetes_incubator/nfs-provisioner:v1.0.7` to `v.1.0.8`, I have the following error: 

```
E0728 14:06:24.627921       5 main.go:111] Error waiting on NFS server process: waitid: no child processes
E0728 14:06:24.628008       5 main.go:114] NFS server stopped unexpectedly, restarting: Pid: 22, ProcessState: <nil>
```

It works with `v1.0.7`.

I use kubeadm 1.7.

**Comment by wongma7** [comment]
Does the error keep repeating? And pod crashes?

**Comment by samuelmanzer** [comment]
I see this too - working on a PR with fix

**Comment by samuelmanzer** [comment]
Working off commit `1575bce47137af89aeb0d81c0a6306acf879b7eb`. 

The issue is this part of `cmd/nfs-provisioner/main.go`: 

```
process, _ := os.FindProcess(pid)
processState, err := process.Wait()
```
In this copy of the `nfs-ganesha` source used by this repo ([https://github.com/nfs-ganesha/nfs-ganesha/archive/V2.4.0.3.tar.gz]) you can see where it daemonizes one of two ways: 


```
#ifdef HAVE_DAEMON
                /* daemonize the process (fork, close xterm fds,
                 * detach from parent process) */
                if (daemon(0, 0))
                        LogFatal(COMPONENT_MAIN,
                                 "Error detaching process from parent: %s",
                                 strerror(errno));

                /* In the child process, change the log header
                 * if not, the header will contain the parent's pid */
                set_const_log_str();
#else
                /* Step 1: forking a service process */
                switch (son_pid = fork()) {
```

In either case, the original (non-daemon) `nfs-ganesha` process terminates, so the `nfs-ganesha` daemon is no longer a descendant of the original provisioner process, and thus cannot be `Wait`ed for. 

Trying to figure out a different way to monitor it.

**Comment by samuelmanzer** [comment]
However, the provisioner still works fine for me, because it ganesha is still running, the provisioner just can't see it running using `Wait`, and keeps trying to restart it.  The log file `/export/ganesha.log` shows this: 

```
31/07/2017 17:55:52 : epoch 597f6f28 : nfs-provisioner-2913128433-rcdpd : nfs-ganesha-6727[main] main :MAIN :FATAL :Ganesha already started
```

**Comment by wongma7** [comment]
ganesha writes to a pid file, the easiest solution may be to read it and watch that specific pid only. The `[-F]                the program stays in foreground` option would prevent that daemon code from executing altogether, we could also try that.

It's weird this issue is host specific because I don't see it.

**Comment by wongma7** [comment]
-F may be added here, I would try that first https://github.com/kubernetes-incubator/external-storage/blob/master/nfs/pkg/server/server.go#L125. Thanks!
