### ISSUE TITLE
Workaround controller for unbinding pending pods' PVCs

### ISSUE THREAD

**Issue by spdeshpande** [kubernetes-incubator/external-storage#301]
Hi @msau42, folks,

Is there a workaround controller available that unbinds PVCs for pods that are stuck in pending? Reference: https://github.com/kubernetes-incubator/external-storage/tree/master/local-volume

**Comment by msau42** [comment]
There was one started here, but not completed because it was low priority:
https://github.com/kubernetes-incubator/external-storage/pull/122

The challenge is how to distinguish between these two conditions:

1. This is the first time we try to launch the pod and we haven't used the PV yet.
2. The pod has mounted the PV before and has data on it, but the pod gets rescheduled for some reason.  We do not want to unbind in this case because the pod will lose its data.

**Comment by spdeshpande** [comment]
Thanks @msau42. Any chances this would be part of the 1.8 release?

**Comment by msau42** [comment]
We don't have anybody working on it.  If anyone wants to take it up, feel free.  It can be developed outside of the main kubernetes repo, so we are not tied to the release schedule.  

However, I would still strongly warn any users of the limitation that we cannot distinguish between an unused PVC vs a used PVC, so there is the potential for data loss by using this controller.

**Comment by spdeshpande** [comment]
Talking out loud here....but instead of a controller, would a DaemonSet work, which:

1. watches for stateful pods stuck in pending state because of specific error predicates
2. finds out the corresponding pv (via pvc)
3. checks if that pv folder is empty (we can mount the parent folder on the daemonset, just like the provisioner)
4. unbind pvc only if #3 is true. 

Thanks,
Sudeep

**Comment by msau42** [comment]
I think that could suffice as a workaround for now.  You can try it out and let us know how it goes.

**Comment by spdeshpande** [comment]
Sure @msau42

**Comment by msau42** [comment]
As of 1.9, this is not needed anymore.
/assign
/close
