### ISSUE TITLE
Possible to change the identity of the provisioner

### ISSUE THREAD

**Issue by jaxxstorm** [kubernetes-incubator/external-storage#40]
I am trying to write a dynamic provisioner which provisions on a shared storage pool (think Gluster/Ceph, but proprietary)

I have the provisioner working on a single node, but i'm not trying to use the leader elect library to make it HA. I want it to run on all the nodes in that provide the storage.

I can get this working easily, however there's a caveat that I can't figure out.

I'm trying to set the provisioner identity to something _repeatable_. I've modelled this code on the cephfs provisioner.

```
type myProvisioner struct {
	identity types.UID
}
func NewMyProvisioner() controller.Provisioner {
	return &myProvisioner{
		identity: uuid.NewUUID(),
	}
}
```

What'd I'd like to do, is set that to something more obvious 

1) If the host reboots for some reason, and then comes back, when the provisioner starts up it'll have a new UUID. This leaves dangling volumes. If I can make the provisioner id repeatable, it can reclaim those volumes when it (if) it returns
2) Alternatively, setting it to the cluster/storage pool name, so that when the master dies, another host can manage the volumes the other provisioner created.

I tried to do this like so:

```
type myProvisioner struct {
	identity string
	cluster string
}
func NewMyProvisioner() controller.Provisioner {
	hostName, err := os.Hostname()
	// we must have a hostname set to identify the pv
	if err != nil {
		panic(err)
	}
	clusterName := os.Getenv("STORAGE_NAME")
	return &myProvisioner{
		// identity of the provisioner is the hostname
		identity: hostName,
		cluster:  clusterName,
	}
}
```

and then in the persistent volume object, I set it like so:
```
pv := &v1.PersistentVolume{
		ObjectMeta: v1.ObjectMeta{
			Name: options.PVName,
			Annotations: map[string]string{
				"ploopProvisionerIdentity": p.identity,
				"ploopClusterName":         p.cluster,
			},
		},
		Spec: v1.PersistentVolumeSpec{
			PersistentVolumeReclaimPolicy: options.PersistentVolumeReclaimPolicy,
			AccessModes:                   options.PVC.Spec.AccessModes,
			Capacity: v1.ResourceList{
				v1.ResourceName(v1.ResourceStorage): options.PVC.Spec.Resources.Requests[v1.ResourceName(v1.ResourceStorage)],
			},
			PersistentVolumeSource: v1.PersistentVolumeSource{
				FlexVolume: &v1.FlexVolumeSource{
					Driver:  "jaxxstorm/ploop", // 
					Options: flexOptions,
				},
			},
		},
	}
```

This didn't work _at all_ and it still generated the exact same identity (a uuid) for the provisioner.

Any ideas? Is this even the right place to ask?

**Comment by wongma7** [comment]
Yes, this is the right place to ask.

When you say it still generated a uuid, I think you are referring to the controller's "identity" which is, confusingly, not supposed to be the same thing as the provisioner's one. https://github.com/kubernetes-incubator/external-storage/blob/master/lib/controller/controller.go#L152. This controller "identity" is more for debugging purposes.

The provisioner "identity" on the other hand is an idea you can do whatever you want with. The  "identity: uuid.NewUUID()" was supposed to be a simple example from the hostPath demo but yeah it won't work if you want your provisioners to survive restarts. So continuing your identity=hostname example: 
* First the provisioner running on host A puts "ploopProvisionerIdentity" on the PV.
* The PV gets claimed, used, etc...
* When it's time for the PV to be reclaimed, every provisioner who is watching the same storage class of PVs will have its `Delete` method called on the PV because the PV has reclaimpolicy Delete and it belongs to that storage class
    * The provisioner running on host A i.e. the provisioner whose identity matches the value of "ploopProvisionerIdentity" is the one who actually attempts to delete the backing storage. If it fails, it returns an error, and Delete gets retried.
    * The other provisioners running on host B,C,D... return IgnoredError to indicate that they are "ignoring" the PV because they know they aren't responsible for deleting backing storage. They shouldn't return any other error because that would lead to 'VolumeFailedDelete' events which are misleading because they didn't even attempt to delete the backing storage, they know there's no point in trying. So they should continue to return IgnoredError until the provisioner who is responsible for the PV, wherever it is, Deletes the PV.

hope this helps. I tried to document this in lib/controller/volume.go but I can see how that was insufficient

**Comment by wongma7** [comment]
I also tried to document this here https://github.com/kubernetes-incubator/external-storage/tree/master/docs/demo/hostpath-provisioner#the-provisioner-interface in the hostPath demo and this is where  "identity: uuid.NewUUID()" came from. I'll change this and ask for cephfs to change it too, because it's not the best example.

**Comment by jaxxstorm** [comment]
I'll give it a try, thanks for the quick response!

**Comment by jaxxstorm** [comment]
@wongma7 is there any chance you can throw together some psuedo code or an example? I'm pretty new to Go :(

**Comment by wongma7** [comment]
@jaxxstorm checkout the Delete logic in nfs-provisioner: https://github.com/kubernetes-incubator/external-storage/blob/master/nfs/pkg/volume/delete.go#L32, the first two blocks

The NFS provisioner stores its identity as a file locally on the host it's running on. So it's pretty analagous to using the host's hostname as the identity.

**Comment by wongma7** [comment]
I updated the demo to get hostname from downward API (hostname of the node the pod is running on, not the pod itself) https://github.com/kubernetes-incubator/external-storage/blob/master/docs/demo/hostpath-provisioner/hostpath-provisioner.go#L57 , take a look for another example

also wrote a lengthy blurb about this identity stuff https://github.com/kubernetes-incubator/external-storage/tree/master/docs/demo/hostpath-provisioner#running-multiple-provisioners-and-giving-provisioners-identities

**Comment by jaxxstorm** [comment]
this got me over the line, and works really well.

thanks for the great responses!
