### ISSUE TITLE
NFS: is volume.beta.kubernetes.io/mount-options annotation supported?

### ISSUE THREAD

**Issue by rutsky** [kubernetes-incubator/external-storage#42]
Kubernetes v1.6 introduces [mount-options](https://github.com/kubernetes/kubernetes.github.io/blob/release-1.6/docs/user-guide/persistent-volumes/index.md#mount-options) annotation, does NFS dynamic provisioner supports them?

**Comment by wongma7** [comment]
Not yet. It could be a storage class parameter. Just a simple comma separated string.

(There is no example to follow upstream atm for how to do this so the caveat is that if we implement this now as a class parameter we may have to change it and break it later.)

**Comment by karthik101** [comment]
Is this still supported yet?

**Comment by dshakey** [comment]
i am interested too, as need to set  no_root_squash

**Comment by wongma7** [comment]
It is a storageclass parameter instead of the storageclass field (I got impatient and added it as a parameter before storageclass.mountoptions existed) https://github.com/kubernetes-incubator/external-storage/blob/master/nfs/docs/usage.md#parameters

In a future update I will add storageclass.mountoptions support and if that is set it will take priority over the parameter

**Comment by wongma7** [comment]
@dshakey also if you need root squash there is a parameter specifically for that as well, see my link.
