### ISSUE TITLE
cephfs provisioner leaks Secret objects

### ISSUE THREAD

**Issue by farcaller** [kubernetes-incubator/external-storage#455]
The cephfs provisioner doesn't clean up Secret objects (doesn't re-use them either), and doesn't clean up the actual users from ceph, leaving them dangling with some permissions:

```
client.kubernetes-dynamic-user-8e229ae4-c4a5-11e7-ad64-0adc8221b842
	key: 
	caps: [mds] allow r
	caps: [mon] allow r
	caps: [osd]
```

Instead the provisioner should return the storage to the same state it was before the PVC was created.

**Comment by wongma7** [comment]
/assign @rootfs 
kind of related, we should no longer be creating secrets in same namespace as pvc anyhow: https://github.com/kubernetes-incubator/external-storage/issues/309

**Comment by rootfs** [comment]
the provisioner [deauthorize](https://github.com/kubernetes-incubator/external-storage/blob/master/ceph/cephfs/cephfs_provisioner/cephfs_provisioner.py#L229) the user when deleting the share. 

Maybe the cap is not all that is expected in the library [here](https://github.com/ceph/ceph/blob/master/src/pybind/ceph_volume_client.py#L1193), since mds is given `allow r` [here](https://github.com/kubernetes-incubator/external-storage/blob/master/ceph/cephfs/cephfs_provisioner/cephfs_provisioner.py#L120) to work around a kernel cephfs issue.

**Comment by rootfs** [comment]
@cofyc do you have a chance to look into this? thanks

**Comment by cofyc** [comment]
@rootfs
OK, I will take a look at it.

**Comment by JrCs** [comment]
My PR #466 only remove ceph user if it's name start with `kubernetes-dynamic-user-`
