### ISSUE TITLE
[local-volume] Deleting PV fails. Cannot find the directory.

### ISSUE THREAD

**Issue by kokhang** [kubernetes-incubator/external-storage#463]
I am using minikube and i have setup 3 directories on the node to be used as local-storage. The directories are in `/mnt/sda1/disks/vol1...3`. I had an issue here described in https://github.com/kubernetes-incubator/external-storage/issues/462 but i have worked around it by editing the PV and correcting the path.

When I deploy an app and use one of these volume, it works well. However when i delete the PVC,
the content in the volume is not deleted. I see the following logs in the provisioner.

```
I1116 00:11:23.355625       1 deleter.go:47] Deleting PV "local-pv-dd4a78d5"
I1116 00:11:23.355655       1 deleter.go:88] Deleting PV "local-pv-dd4a78d5" contents at hostpath "/mnt/sda1/disks/vol2", mountpath "/sda1/disks/vol2"
E1116 00:11:23.355675       1 deleter.go:53] Error cleaning PV "local-pv-dd4a78d5": open /sda1/disks/vol2: no such file or directory
```
I am not sure why it is trying to access `/sda1/disks/vol2` since the local path dir is at  `/mnt/sda1/disks/vol2`.

**Comment by msau42** [comment]
There's the path of the directory on the host, the "hostpath".  And the directory that the hostpath gets mounted at in the provisioner container, the "mountpath".

This problem might be related to the fallback on the default paths.  The hostpath and mountpath mappings need to be specified correctly in the configmap, so that we launch the provisioner with the correct hostpath volume config.

**Comment by kokhang** [comment]
This was a symptom of issue #462. Closing.
