### ISSUE TITLE
dynamic provisioner for externally managed NFS 

### ISSUE THREAD

**Issue by HardikDR** [kubernetes-incubator/external-storage#5]
Current NFS provisioner , either creates the nfs-ganesha or expects the kernel nfs-server running on the node. 

I would like to propose the out of tree provisioner , which can dynamically provision volumes on the externally managed nfs-server. Provisioner would create directories over NFS mount-point  corresponding to the PVCs being created . Each directory would be mapped to the PV object , which in turn is bounded to the PVC, similar flow as of the existing provisioner. Can be seen as a simple mkdir-provisioner.

Usecase : In cases where NFS , glusterFS etc are managed  by the separate teams and k8s user gets only the necessary authorization and mountpoints for consuming such File Systems. There is no direct access to the server. K8s should have ready-made mkdir-provisioners which can just provision volumes over such FileSystems. 

Example Flow: 
--> NFS share provided to k8s user :  nfsserver:/data

--> nfserver:/data mounted to the   /exports (inside the provisioner-pod).

--> With creation of the new PVC named pvc-0 , provisioner :
      - creates directory /exports/pvc-0
      - creates PV object mounted to the nfsserver:/data/pvc-0 . 
      - PVC gets bound to PV.

Downsides specific to NFS :  
--> Quota :  Quota management would be hard , as each PV on NFS is just a directory and not the NFS share created by the NFS server. 
--> Security : Pod consuming the PVC would have root access to the NFS mount. Privileged Pod can mess up with the directories associated with rest of the PVs (by just mounting the pod again to the NFS share.)

Code should follow the specification mentioned here: https://github.com/kubernetes-incubator/external-storage/tree/master/docs/demo/hostpath-provisioner , 
https://github.com/jsafrane/kubernetes/blob/95197536fc5be791e474b952aa939ac7a2299d7e/docs/proposals/volume-provisioning.md

I understand this provisioner would be just the subset of the existing nfs-provisioner but particular usecase is important if user is fine with the mentioned Quota and Security issue for now.
 
Does it sound good enough to have a separate directory in here , which basically consists of such provisioners , say for nfs (for now)? 
I would love to create  PR if this sounds good enough !!

cc @jsafrane 

Thanks

**Comment by wongma7** [comment]
cc https://github.com/kubernetes-incubator/nfs-provisioner/issues/85

**Comment by wongma7** [comment]
I think this is out of scope of 'nfs-provisioner' and should be another provisioner/directory. The only issue is naming...

Correct me if I'm wrong, the assumption/prerequisite to this working is that the NFS server will allow you to mount sub-directories of an export without you having to explicitly creating export entries for each subdirectory? (Is that in an NFS spec somewhere, I have no idea.)

Because this is exactly how my EFS provisioner works https://github.com/wongma7/efs-provisioner . Except of course it's restricted to EFS simply because it checks with AWS that your EFS  filesystem exists in the first place.

RE: quota; I think this is okay, there shouldn't be an expectation that quota works with NFS. (The quota feature of nfs-provisioner is basically a bonus, idk if anyone actually uses it.) It should be the responsibility of whoever is managing the NFS server to quota the dirs they give k8s (the provisioner, etc.) access to.

RE: security: if pod has access only to the pvc specific directory, it can't go up and mess with other pvc directories can it? The way efs provisioner 'does security' is it assigns every PV a GID, and any pod who consumes the PVC+PV gets that GID as a supplemental group. Honestly if there are privileged pods in the cluster I think security basically doesn't exist anymore anyway

**Comment by HardikDR** [comment]
https://github.com/kubernetes-incubator/nfs-provisioner/issues/85#issuecomment-283098593
@wongma7  I would suggest to have a separate directory in here , which basically consists of the only such type of provisioners. We may need better name though.
So we can include better range of such provisioners based on different filesystems.

**Comment by wongma7** [comment]
yeah I mean EFS too is technically NFS . so should the provisioners be divided by filesystem/plugin type or... not sure yet. Regardless yeah we agree it should be a separate directory

**Comment by HardikDR** [comment]
I would suggest it should be divided based on the FileSystem type AND 
whether provisioner manages server   or only behaves as a client to the external server. 
How about /externalstorage/client-provisioners/nfs-client-provisioner ??!!??

**Comment by wongma7** [comment]
I think the client-only vs server idea is specific to NFS so won't be too useful to divide by that. Anyway, I would prefer it to get its own top-level directory now (externalstorage/nfs-client-provisioner), and we can postpone the decision for whether to further divide provisioners if/when the repo gets too crowded. That way it will be easier to discover.

I will be adding my efs provisioner to the repo soon. I don't think you necessarily need to fork it or anything like that but keep in mind it does pretty much exactly the same thing as this proposed provisioner. At least, I think you should copy the GID allocator stuff from it (gidMin & gidMax) for some of the security issues. (in fact the GID allocator stuff is already copied from upstream's Gluster provisioner)

**Comment by HardikDR** [comment]
Yes sure !! 
Sounds good.

**Comment by jackielii** [comment]
hi I created a simple and naive version based on @wongma7's efs:
https://github.com/jackielii/client-nfs-provisioner 

I'm happy to contribute it to this repo.

Regards

**Comment by wongma7** [comment]
Sounds good to me. I added docs on adding to this repo just a few days ago: https://github.com/kubernetes-incubator/external-storage/tree/master/docs#contributing.

When you are checking it in, you will have to update the NewProvisionController signature so that it can build with lib master since I just updated it today in preparation for lib 3.0.0.

**Comment by manishg4** [comment]
Did someone figure out how to have a quota setup on the new directory being created for the container such that the container which gets linked with the directory has only access to the size specified in the PV and not the size of the entire NFS share ?
