### ISSUE TITLE
dynamic provisioning of storage

### ISSUE THREAD

**Issue by rangapv** [kubernetes-incubator/external-storage#632]
I am trying to install concourse ci on kuberenetes GCE with kuebadm init install......

Which method and how to enable Dynamic provisioning....

My current state of mind...

There is

1. kubernetes-incubator/external-storage/local-volume/provisioner/deployment/kubernetes/
with...
 gce
 admin_account.yaml
 example-storage.yaml
 provisioner-daemonset.yaml

2. in the same direcory there is external-storage/local-volume/provisioner/deployment/docker
with...
 Dockerfile

3. There is a pkg in kubernetes-incubator/external-storage/local-volume/provisioner/pkg/
with...
     common
     discovery
     deleter
    etc....

4. Then there is 
   the external-storage/local-volume
       with 
           helm
           provisioner
           examples

Now for the purpose of achieving dynamic provisioning pls tell me the steps 

( the one and only files that needs to be downloaded and the corresponding steps for each of the following)
 If I want to do helm chart install the files that needs to be downloaded and the matching steps
 If I want to do a kubectl apply insted the files that needs to be downloaded and the matching steps..
 If I want to do Make/compile the files that needs to be downlaoded and the matching steps...
)

Assuming the Kubeadm init was the method followed to bring up the cluster.

I wish there was a wrapper for this......

Regards
Ranga

**Comment by msau42** [comment]
Do you want to use GCE local SSDs or GCE Persistent Disks?

**Comment by rangapv** [comment]
For Dynamic volume provisioning I want to use GCE localSSDs and for static I want to use GCE Persistent disk, basically both.. :-) 
Regards
Ranga

**Comment by msau42** [comment]
So local storage does not support dynamic provisioning yet, only static provisioning.  What this means is that the local storage provisioner will detect each local SSD on each node, and create one PV per local SSD.  It cannot dynamically carve out smaller chunks of local SSD. We are trying to target alpha support for dynamic provisioning in 1.11.

In the meantime, if you need smaller chunks, then one option you can do is to have a node setup script that will partition a local ssd, but still that is static, not dynamic provisioning.

What is your use case for using local SSD?  Is it only for caching, or do you need some persistence  and data gravity?  If it's the former, then another option you could try is to install Kubernetes on top of the local SSD instead of the PD boot disk, and then use Emptydir for your pods.  Note, this is just an idea, I have not tried this myself.

After all this, if you still want to use the local volume static provisioner, then I can help you with that, however, I am not familiar with kubeadm deployments.  At least with gke and kube-up, we have node setup scripts that will automatically format and mount the local SSDs.  If kubeadm does not do that, then you will have to write your own setup scripts or copy the pieces you need from the configure-vm script.  

The README walks through the provisioner bring up step by step, but the gce instructions assume either using kube-up or GKE.  If kubeadm does something similar, then you can reuse those steps, otherwise you may need to do something closer to the baremetal steps.
