### ISSUE TITLE
Should vendor directory be committed?

### ISSUE THREAD

**Issue by YiannisGkoufas** [kubernetes-incubator/external-storage#827]
More of a question, and less an issue.
I was trying to follow the guide here https://github.com/kubernetes-incubator/external-storage/tree/master/docs/demo/hostpath-provisioner but got stuck because the k8.io/api was included both in 2 vendors folders (the parent of my project and the one under this repo)
So I had to create a fork ( https://github.com/YiannisGkoufas/external-storage/tree/v3.2 ) from which I deleted the vendor directory and replaced the references to github.com/kubernetes-incubator/external-storage and I got it working

**Comment by wongma7** [comment]
the hostpath provisioner has its own glide.yaml, if you run glide install -v in that directory then the generated vendor should take precedence over any other. The guide might be outdated is the main problem, what versions specifically are in conflict? I don't think it is needed to replace references, I believe you should be able to just delete the problematic dependencies like k8s.io/api from the vendor directory and things should build fine.

for external-storage in general, we check it in because...installing vendor can take a long time even with glide.yaml & glide.lock provided, and figuring out kube dependencies has been historically hard in case there is some conflict during install, so we just provide it and let you decide what to do with it at the cost of some MB (checking now, it seems the last time we updated dependencies nobody ran glide-vc so it's much bigger than expected...). Note there are two conflicting goals of this repo, 1 is to provide the library in which case the vendor dir is not needed, 2 is to house provisioners for which the vendor dir ensures reproducible builds
