### ISSUE TITLE
NFS PVC created pre upgrade to 4.1, always mount as 4.0

### ISSUE THREAD

**Issue by patrickdk77** [kubernetes-incubator/external-storage#906]
Only new PVC's created after upgrading external-storage pod, get created and mounted using nfs 4.1
All PVC's created prior to the upgrade, continue to mount using NFS 4.0, even after all nodes and pods have been shutdown, deleted and recreated.

Do we have to recreate all the PVC's, or is there a way to upgrade the mount options? @

**Comment by wongma7** [comment]
The PVs need to be edited so that their spec.mountOptions includes "vers=4.1" but IDK if the field is even mutable. And on top of that the pods need to be restarted. (I said somewhere else that pods restarting was sufficient to get them to remount v4.1, that's wrong and if I can find that comment I will edit it...)

/area aws/efs
