### ISSUE TITLE
GKE Node upgrades causes repeat "PV exists" error

### ISSUE THREAD

**Issue by dwilliams782** [kubernetes-incubator/external-storage#945]
When upgrading a GKE node pool configured with local SSDs, the nodes are drained, deleted and recreated. When they come back up, the rescheduled Pod errors with "persistentvolumes x already exists"; this will loop continuously until the PV is manually deleted. 

Deleting a bound PVC has no affect on the PV; the PV will remain in a "Released" state until manually deleted.

Is this a known issue?

**Comment by wongma7** [comment]
what pod is giving that error?

**Comment by dwilliams782** [comment]
The DaemonSet pod for the Local Volume Static Provisioner:

![image](https://user-images.githubusercontent.com/42545485/44347090-e9d28780-a48e-11e8-959b-44bdf0a3ef4b.png)

Workflow:

*Pod is scheduled, PV is successfully created
*StatefulSet using volumeClaimTemplates creates a PVC and binds to our PV
*Trigger a Node Pool upgrade
*Node is restarted, pod is rescheduled
*Pod tries to create PV with the same name

**Comment by wongma7** [comment]
/area local-volume
Does the node UID remain the same before/after upgrade? The name does, right? A different UID would explain this error.

**Comment by msau42** [comment]
Yes, I think there is at least one issue here.

In 1.10 (and below), when a node upgrade or repair was done, the Kubernetes Node object would be recreated (and therefore get a new Node.UID).  The local volume provisioner filters out local PV objects that were not created by the provisioner on its current Node UID, which is inconsistent with local PV naming scheme, which only uses Node.Name.  I opened up #636 to add an option to set provisioner name without node UID to solve this cleanup issue.  However, this will only fix new deployments going forward.  Existing PVs created with an older local provisioner will still have the UID provisioner naming.

This issue should not be seen on 1.11 because Node objects are no longer recreated on upgrade/repair even though the underlying instance is still recreated (and local SSDs are wiped).  Regardless, fixing #636 should not impact 1.11, so we should fix it anyway.

Eventually when GKE offers a unique local SSD naming scheme, using Node.Name will still be fine because the local SSDs will have unique paths.  So on an upgrade/repair, a new PV will get created, and the stale PV will remain with error.

**Comment by msau42** [comment]
HI @dwilliams782, we added an option to not use Node UID in the provisioner name in #947, and I updated the GKE provisioner spec to use it in #952.  This won't solve the problem with Local PVs created by the older version of the provisioner, so you will have to delete those PVs when after deleting the PVCs, or update all of the PVs with the correct provisioner name in the "provisioned-by" annotation

**Comment by msau42** [comment]
Let me know if you are still seeing issues.

**Comment by msau42** [comment]
Please open a new issue in https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner if you still have problems.

/close
