### ISSUE TITLE
ProvisionController: refactoring using SharedInformers

### ISSUE THREAD

**Issue by iawia002** [kubernetes-incubator/external-storage#967]
Hi, I'd like to propose refactoring `ProvisionController` using `SharedInformers` totally.

As mentioned in the controller's Guidelines:

> This saves us connections against the API server, duplicate serialization costs server-side, duplicate deserialization costs controller-side, and duplicate caching costs controller-side.

If this sounds reasonable, I'd be happy to work on this.

/cc @wongma7

**Comment by wongma7** [comment]
Yes this is okay with me, thank you for your help. I thought briefly about it. Like, we create a SharedInormer instead of NewInformer here, maybe using those factory functions provided by client-go https://github.com/kubernetes-incubator/external-storage/blob/master/lib/controller/controller.go#L504

I am skeptical of the savings for us though: the controller is not "sharing" the informers with any other controllers, so still we need to create our own connection to the API server (I think it means that in controller-manager, multiple controllers can use the same connection). As for deserialization and caching I'm not sure. Either way we should move to SharedInformers just because they are the "correct" interface for using informers.

**Comment by iawia002** [comment]
Thanks for the explanation, I'll submit a PR soon
